name: Multi-Event Workflow
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
  schedule:
    - cron: "0 12 * * 1" # Runs every Monday at 12:00 UTC

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Event
        run: echo "This workflow was triggered by ${{ github.event_name }}"
