name: Dependent Jobs Example

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building the application"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Running tests"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Deploying application"
